### ISSUE TITLE
Problem in getting 'deposits' ?

### ISSUE THREAD

**Issue by anazhd** [BenjiLee/PoloniexAnalyzer#2]
```
Traceback (most recent call last):
  File "poloniex.py", line 35, in <module>
    class main():
  File "poloniex.py", line 42, in main
    dw_history.get_btc_total(),
  File "/home/ubuntu/PoloniexAnalyzer/deposit_withdrawal_history.py", line 9, in get_btc_total
    for deposit in self.history['deposits']:
KeyError: 'deposits'

```

**Comment by BenjiLee** [comment]
Master branch is working for me. Your key/secret isn't configured correctly. 

Going to add better error messages.

**Comment by BenjiLee** [comment]
Added errors in https://github.com/BenjiLee/PoloniexAnalyzer/commit/2d28692f83ac0fe767e6f604263184df45d45fe5

**Comment by BenjiLee** [comment]
Also updated the way the key and secret can be added so it's clearer.
