### ISSUE TITLE
poloniex.py errors

### ISSUE THREAD

**Issue by dt2017** [BenjiLee/PoloniexAnalyzer#30]
Hi
Have cloned your project to Ubuntu 16, updated the api_keys.ini file as requested
run, python poloniex.py -a GetOverview
and get the follow error
Any thoughts?
Traceback (most recent call last):
  File "poloniex.py", line 64, in <module>
    main()
  File "poloniex.py", line 56, in main
    actions[args.action]['function']()
  File "/home/dtadmin/PoloniexAnalyzer/analyzer.py", line 24, in get_overview
    balances = Balances(trading_api.return_complete_balances())
  File "/home/dtadmin/PoloniexAnalyzer/poloniex_apis/trading_api.py", line 37, in return_complete_balances
    return _call_trading_api(body)
  File "/home/dtadmin/PoloniexAnalyzer/poloniex_apis/trading_api.py", line 86, in _call_trading_api
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422:

**Comment by BenjiLee** [comment]
https://github.com/BenjiLee/PoloniexAnalyzer/issues/24

You need to create a new api key for this script.
