### ISSUE TITLE
ERROR: 422

### ISSUE THREAD

**Issue by jtelo88** [BenjiLee/PoloniexAnalyzer#31]
Hi,

I got this error when try to run you software.

python poloniex.py -a GetOverview
Traceback (most recent call last):
  File "poloniex.py", line 64, in <module>
    main()
  File "poloniex.py", line 56, in main
    actions[args.action]['function']()
  File "/home/jtelo/PoloniexAnalyzer/analyzer.py", line 24, in get_overview
    balances = Balances(trading_api.return_complete_balances())
  File "/home/jtelo/PoloniexAnalyzer/poloniex_apis/trading_api.py", line 37, in return_complete_balances
    return _call_trading_api(body)
  File "/home/jtelo/PoloniexAnalyzer/poloniex_apis/trading_api.py", line 86, in _call_trading_api
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422:

What do you think this problem are?

Thanks for your help doing this!!

**Comment by BenjiLee** [comment]
https://github.com/BenjiLee/PoloniexAnalyzer/issues/24

Try adding a new API key to poloniex. Poloniex requires a value for a parameter in a request that is greater than the previous. If you have used a different script it possible that this value was set differently than the scripts in this repo.
